# Generated by Django 5.0.2 on 2024-05-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='next_update_photo_time',
            field=models.DateTimeField(verbose_name='Дата, когда обновляем фотографию'),
        ),
    ]
